"""Configurable candidate profiles for GetInlets V3.

Profiles are plain dictionaries for now so the matcher can be proven independently
of authentication and onboarding. Later these values will be loaded from db.Profile.
"""

CYBERSECURITY_BETA_PROFILE = {
    "name": "Cybersecurity Beta",
    "career_field": "cybersecurity",
    "target_titles": [
        "soc analyst",
        "soc analyst i",
        "tier 1 soc analyst",
        "junior security analyst",
        "security operations analyst",
        "security operations center analyst",
        "security operations centre analyst",
        "cyber security operations center analyst",
        "cyber security operations centre analyst",
        "cybersecurity analyst",
        "cyber security analyst",
        "mdr analyst",
        "mssp security analyst",
        "incident response analyst",
        "detection analyst",
        "security monitoring analyst",
    ],
    "conditional_titles": [
        "security specialist",
        "information security analyst",
        "threat analyst",
        "security consultant",
        "cyber defense analyst",
        "cyber defence analyst",
    ],
    "excluded_titles": [
        "senior",
        "sr.",
        "sr ",
        "lead",
        "principal",
        "staff",
        "manager",
        "director",
        "architect",
        "application security",
        "appsec",
        "product security",
        "devsecops",
        "penetration tester",
        "penetration testing",
        "red team",
        "iam",
        "identity governance",
        "grc",
        "security compliance",
    ],
    "max_required_years": 4,
    "preferred_locations": [
        "toronto",
        "north york",
        "scarborough",
        "etobicoke",
        "mississauga",
        "brampton",
        "markham",
        "vaughan",
        "richmond hill",
        "pickering",
        "ajax",
        "whitby",
        "oshawa",
        "oakville",
        "milton",
        "burlington",
    ],
    "nearby_ontario_locations": [
        "st. jacobs",
        "st jacobs",
        "waterloo",
        "kitchener",
        "cambridge",
        "guelph",
        "hamilton",
    ],
    "remote_preference": "canada_remote",
    # Confirmed-profile skills should eventually come from the user's parsed resume
    # and onboarding answers. The beta values below reflect the current test profile.
    "skills": [
        "microsoft sentinel",
        "splunk",
        "crowdstrike",
        "siem",
        "xdr",
        "edr",
        "alert triage",
        "incident response",
        "incident escalation",
        "phishing",
        "malware",
        "ticket lifecycle",
        "windows",
        "linux",
        "ids/ips",
        "firewalls",
        "vpn",
        "mitre att&ck",
        "client-facing remediation",
    ],
    # Keep certifications explicit. Do not infer credentials from job-description text.
    "certifications": [],
}
